import React, { useState } from 'react';
import { T, MONO, SANS } from '../../theme/tokens';
import { TEAM } from '../../data/team';
import { FUNDS_SEED } from '../../data/funds';
import { FieldLabel } from '../primitives/Card';

export function AuditorPortal({onClose}) {
  const [step,setStep]=useState("login");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [mfaCode,setMfaCode]=useState("");const [loginErr,setLoginErr]=useState("");const [downloading,setDownloading]=useState<string|null>(null);
  const handleLogin=()=>{ if(!email.includes("@")||!password){setLoginErr("Please enter a valid email and password.");return;} setLoginErr("");setStep("mfa"); };
  const handleMfa=()=>{ if(mfaCode.length!==6){setLoginErr("Enter the 6-digit code.");return;} setLoginErr("");setStep("portal"); };
  const handleDownload=label=>{ setDownloading(label);setTimeout(()=>setDownloading(null),1400); };
  const REPORTS=[{id:"r1",label:"Trial Balance — Dec 31, 2024",type:"Excel",fund:"Pennywise Global Diversified Fund",date:"Jan 1, 2025",icon:"📊"},{id:"r2",label:"Audited Financial Statements Draft",type:"PDF",fund:"Pennywise Global Diversified Fund",date:"Jan 2, 2025",icon:"📄"},{id:"r3",label:"Schedule of Investments",type:"Excel",fund:"Pennywise Global Diversified Fund",date:"Jan 1, 2025",icon:"📊"},{id:"r4",label:"Exception Resolution Audit Trail",type:"PDF",fund:"Pennywise Global Diversified Fund",date:"Jan 2, 2025",icon:"🔍"},{id:"r5",label:"Fair Value Hierarchy Rollforward",type:"Excel",fund:"Pennywise Global Diversified Fund",date:"Jan 1, 2025",icon:"📊"}];
  return <div className="modal-overlay" role="dialog" aria-modal="true" style={{position:"fixed",inset:0,background:"rgba(10,18,30,0.85)",zIndex:900,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={onClose}>
    <div onClick={e=>e.stopPropagation()} style={{background:T.cardBg,borderRadius:14,width:step==="portal"?640:420,boxShadow:"0 30px 80px rgba(0,0,0,0.4)",overflow:"hidden",maxHeight:"90vh",display:"flex",flexDirection:"column"}}>
      <div style={{background:T.navyHeader,padding:"18px 22px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{...SANS,fontWeight:700,fontSize:15,color:"#fff",display:"flex",alignItems:"center",gap:8}}><span style={{color:T.actionBase}}>T</span>ORRANCE<span style={{...SANS,fontSize:11,fontWeight:600,padding:"2px 8px",borderRadius:4,background:"#0d1724",color:"#8898aa"}}>Auditor Portal</span></div><div style={{...SANS,fontSize:11,color:"#8898aa",marginTop:2}}>Read-only · PricewaterhouseCoopers LLP</div></div><button onClick={onClose} aria-label="Close" style={{background:"none",border:"none",color:"#8898aa",cursor:"pointer",fontSize:18}}>✕</button></div>
      {step==="login"&&<div style={{padding:"28px 28px 32px"}}><div style={{...SANS,fontSize:13,color:T.textMuted,marginBottom:20,lineHeight:1.6}}>Secure, read-only portal for authorized external auditors. Access is logged and monitored.</div>{loginErr&&<div style={{...SANS,fontSize:12,color:T.errorBase,background:T.errorBg,border:`1px solid ${T.errorBorder}`,borderRadius:6,padding:"8px 12px",marginBottom:14}}>{loginErr}</div>}<div style={{marginBottom:14}}><FieldLabel>Auditor Email</FieldLabel><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@pwc.com" style={{...SANS,width:"100%",border:`1px solid ${T.border}`,borderRadius:6,padding:"10px 12px",fontSize:13}}/></div><div style={{marginBottom:20}}><FieldLabel>Password</FieldLabel><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" style={{...SANS,width:"100%",border:`1px solid ${T.border}`,borderRadius:6,padding:"10px 12px",fontSize:13}} onKeyDown={e=>e.key==="Enter"&&handleLogin()}/></div><button onClick={handleLogin} style={{...SANS,width:"100%",border:"none",borderRadius:7,padding:"12px",fontSize:13,fontWeight:700,background:T.actionBase,color:"#fff",cursor:"pointer"}}>Sign In</button><div style={{...SANS,fontSize:11,color:T.textMuted,textAlign:"center",marginTop:12,display:"flex",alignItems:"center",gap:6,justifyContent:"center"}}><span>🔒</span>Secured with TLS 1.3 · SOC 2 Type II compliant</div></div>}
      {step==="mfa"&&<div style={{padding:"28px 28px 32px"}}><div style={{textAlign:"center",marginBottom:22}}><div style={{fontSize:32,marginBottom:10}}>📱</div><div style={{...SANS,fontWeight:700,fontSize:15,marginBottom:6}}>Two-Factor Authentication</div><div style={{...SANS,fontSize:13,color:T.textMuted}}>Enter the 6-digit code from your authenticator app.</div></div>{loginErr&&<div style={{...SANS,fontSize:12,color:T.errorBase,background:T.errorBg,border:`1px solid ${T.errorBorder}`,borderRadius:6,padding:"8px 12px",marginBottom:14,textAlign:"center"}}>{loginErr}</div>}<input type="text" maxLength={6} value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,""))} placeholder="000000" style={{...MONO,width:"100%",border:`1px solid ${T.border}`,borderRadius:8,padding:"14px 12px",fontSize:22,textAlign:"center",letterSpacing:"0.3em",marginBottom:16}} onKeyDown={e=>e.key==="Enter"&&handleMfa()}/><button onClick={handleMfa} style={{...SANS,width:"100%",border:"none",borderRadius:7,padding:"12px",fontSize:13,fontWeight:700,background:T.actionBase,color:"#fff",cursor:"pointer"}}>Verify Code</button><button onClick={()=>{setMfaCode("");setLoginErr("");setStep("login");}} style={{...SANS,width:"100%",border:"none",background:"transparent",color:T.textMuted,fontSize:12,padding:"10px",cursor:"pointer",marginTop:4}}>← Back to login</button></div>}
      {step==="portal"&&<div style={{overflowY:"auto"}}>
        <div style={{padding:"16px 22px",borderBottom:`1px solid ${T.border}`,display:"flex",alignItems:"center",justifyContent:"space-between",background:"#fafbff"}}><div><div style={{...SANS,fontWeight:700,fontSize:13}}>Available Reports</div><div style={{...SANS,fontSize:11,color:T.textMuted,marginTop:1}}>Read-only · All downloads are logged</div></div><span style={{...SANS,fontSize:11,fontWeight:700,padding:"4px 10px",borderRadius:5,background:T.okBg,color:T.okBase,border:`1px solid ${T.okBorder}`,display:"flex",alignItems:"center",gap:4}}><span>✓</span>Authenticated</span></div>
        <div style={{padding:"16px 22px"}}>{REPORTS.map(r=>(
          <div key={r.id} style={{display:"flex",alignItems:"center",gap:13,padding:"12px 14px",borderRadius:8,border:`1px solid ${T.border}`,marginBottom:9,background:T.cardBg}}>
            <span style={{fontSize:22,flexShrink:0}}>{r.icon}</span><div style={{flex:1}}><div style={{...SANS,fontWeight:700,fontSize:13,marginBottom:2}}>{r.label}</div><div style={{...SANS,fontSize:11,color:T.textMuted}}>{r.fund} · {r.date}</div></div>
            <span style={{...MONO,fontSize:10,fontWeight:700,padding:"2px 7px",borderRadius:3,background:r.type==="PDF"?T.errorBg:T.okBg,color:r.type==="PDF"?T.errorBase:T.okBase,border:`1px solid ${r.type==="PDF"?T.errorBorder:T.okBorder}`}}>{r.type}</span>
            <button onClick={()=>handleDownload(r.id)} style={{...SANS,fontSize:12,fontWeight:600,padding:"6px 14px",borderRadius:5,border:`1px solid ${T.border}`,background:downloading===r.id?T.okBg:T.cardBg,color:downloading===r.id?T.okBase:T.textPrimary,cursor:"pointer",display:"flex",alignItems:"center",gap:5,transition:"all 0.15s",whiteSpace:"nowrap"}}>{downloading===r.id?<><span>✓</span>Downloaded</>:<><span>↓</span>Download</>}</button>
          </div>
        ))}</div>
      </div>}
    </div>
  </div>;
}

