import React, { useState } from 'react';
import { T, MONO, SANS } from '../../theme/tokens';
import { TEAM } from '../../data/team';
import { SOC1_ACCESS_LOG, SOC1_AI_STATS } from '../../data/aiData';
import { Avatar } from '../primitives/Avatar';

export function Soc1AuditReport({onClose, fundState, approvalState, fundSeeds}) {
  const [generating, setGenerating] = useState(false);
  const [generated,  setGenerated]  = useState(false);

  const totalResolved  = (Object.values(fundState) as any[][]).flat().filter((e:any)=>e.status==="resolved").length;
  const totalOpen      = (Object.values(fundState) as any[][]).flat().filter((e:any)=>e.status==="open").length;
  const totalOverrides = (Object.values(fundState) as any[][]).flat().filter((e:any)=>e.resolution==="override_value").length;
  const approvedFunds  = Object.values(approvalState).filter((a:any)=>a.status==="approved").length;

  const handleGenerate = () => { setGenerating(true); setTimeout(()=>{ setGenerating(false); setGenerated(true); },1800); };

  const Section = ({title, children}) => (
    <div style={{marginBottom:22}}>
      <div style={{...SANS,fontWeight:700,fontSize:13,color:T.navyHeader,paddingBottom:6,borderBottom:`2px solid ${T.border}`,marginBottom:12}}>{title}</div>
      {children}
    </div>
  );

  const StatRow = ({label, val, note=null}: {label: any; val: any; note?: string | null}) => (
    <div style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:`1px solid ${T.border}`}}>
      <span style={{...SANS,fontSize:12,color:T.textPrimary}}>{label}</span>
      <div style={{textAlign:"right"}}>
        <span style={{...MONO,fontSize:12,fontWeight:700,color:T.textPrimary}}>{val}</span>
        {note&&<div style={{...SANS,fontSize:10,color:T.textMuted}}>{note}</div>}
      </div>
    </div>
  );

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" style={{position:"fixed",inset:0,background:"rgba(26,35,50,0.7)",zIndex:800,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={onClose}>
      <div onClick={e=>e.stopPropagation()} style={{background:T.cardBg,borderRadius:12,width:680,maxHeight:"90vh",display:"flex",flexDirection:"column",boxShadow:"0 20px 60px rgba(0,0,0,0.3)",overflow:"hidden"}}>
        <div style={{background:T.navyHeader,padding:"16px 22px",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
          <div>
            <div style={{...SANS,fontWeight:700,fontSize:15,color:"#fff"}}>SOC 1 Type II — Internal Controls Report</div>
            <div style={{...SANS,fontSize:11,color:"#8898aa",marginTop:2}}>December 31, 2024 · Generated by Torrance</div>
          </div>
          <div style={{display:"flex",gap:10,alignItems:"center"}}>
            <button onClick={handleGenerate} disabled={generating}
              style={{...SANS,fontSize:12,fontWeight:700,padding:"8px 16px",borderRadius:6,border:"none",background:generating?"#374151":generated?T.okBase:T.actionBase,color:generating?"#6b7280":"#fff",cursor:generating?"not-allowed":"pointer",display:"flex",alignItems:"center",gap:6}}>
              {generating?<><span style={{animation:"pulse 0.8s infinite"}}>●</span>Generating…</>:generated?<><span>✓</span>Re-download</>:<><span>↓</span>Download PDF</>}
            </button>
            <button onClick={onClose} style={{background:"none",border:"none",color:"#8898aa",cursor:"pointer",fontSize:18}}>✕</button>
          </div>
        </div>

        <div style={{overflowY:"auto",flex:1,padding:"24px 28px"}}>
          <Section title="1. Scope and Period">
            <p style={{...SANS,fontSize:12,color:T.textPrimary,lineHeight:1.75}}>
              This report covers the operations of the Torrance fund accounting platform for the period ending <strong>December 31, 2024</strong>. The controls described herein govern the ingestion, validation, exception resolution, and approval of general ledger data for <strong>{fundSeeds.length} funds</strong> across {[...new Set(fundSeeds.map(f=>f.client))].length} client relationships.
            </p>
          </Section>

          <Section title="2. Exception Resolution Controls">
            <StatRow label="Total exceptions raised"       val={totalResolved+totalOpen}/>
            <StatRow label="Exceptions resolved"           val={totalResolved}/>
            <StatRow label="Exceptions open (pending)"     val={totalOpen}/>
            <StatRow label="Override resolutions"          val={totalOverrides} note="Each override requires a manual value entry"/>
            <StatRow label="Funds approved"                val={`${approvedFunds} of ${fundSeeds.length}`}/>
          </Section>

          <Section title="3. AI Assistance Controls">
            <StatRow label="AI suggestions surfaced"       val={SOC1_AI_STATS.totalSuggestions}/>
            <StatRow label="Suggestions accepted"          val={SOC1_AI_STATS.accepted} note={`${SOC1_AI_STATS.acceptanceRate}% acceptance rate`}/>
            <StatRow label="Suggestions dismissed"         val={SOC1_AI_STATS.dismissed}/>
            <StatRow label="Auto-accepted (≥95% conf.)"   val={SOC1_AI_STATS.autoAccepted}/>
            <div style={{marginTop:10,padding:"9px 12px",borderRadius:6,background:T.okBg,border:`1px solid ${T.okBorder}`}}>
              <span style={{...SANS,fontSize:11,color:T.okBase,fontWeight:500}}>
                All AI suggestions are logged with their confidence score, prior-period basis, and resolution outcome. No suggestion was auto-applied above the 95% threshold during this period.
              </span>
            </div>
          </Section>

          <Section title="4. User Access Log">
            <div style={{background:T.appBg,border:`1px solid ${T.border}`,borderRadius:8,overflow:"hidden"}}>
              <table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}>
                <thead>
                  <tr style={{background:"#f0f2f5"}}>
                    {["Timestamp","User","Action","Detail"].map(h=>(
                      <th key={h} style={{...SANS,padding:"7px 10px",textAlign:"left",color:T.textMuted,fontWeight:700,fontSize:10,textTransform:"uppercase",letterSpacing:"0.05em",borderBottom:`1px solid ${T.border}`}}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {SOC1_ACCESS_LOG.map((log,i)=>{
                    const user = TEAM.find(m=>m.id===log.user);
                    return (
                      <tr key={i} style={{background:i%2===0?T.cardBg:T.appBg}}>
                        <td style={{...MONO,padding:"7px 10px",fontSize:10,color:T.textMuted,borderBottom:`1px solid ${T.border}`,whiteSpace:"nowrap"}}>{log.ts}</td>
                        <td style={{padding:"7px 10px",borderBottom:`1px solid ${T.border}`}}>
                          {user&&<div style={{display:"flex",alignItems:"center",gap:5}}><Avatar user={user} size={18}/><span style={{...SANS,fontSize:11,color:T.textPrimary}}>{user.name}</span></div>}
                        </td>
                        <td style={{padding:"7px 10px",borderBottom:`1px solid ${T.border}`}}>
                          <span style={{...SANS,fontSize:11,fontWeight:600,color:T.textPrimary}}>{log.action}</span>
                        </td>
                        <td style={{...SANS,padding:"7px 10px",fontSize:10,color:T.textMuted,borderBottom:`1px solid ${T.border}`}}>{log.detail}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </Section>

          <Section title="5. Certification">
            <p style={{...SANS,fontSize:12,color:T.textPrimary,lineHeight:1.75}}>
              The controls described in this report were operating effectively during the period under review. All exception resolutions were performed by authorized personnel. AI-assisted resolutions were reviewed and accepted by a human preparer prior to submission. The final approval workflow required Controller sign-off before any fund was marked Approved.
            </p>
            <div style={{marginTop:16,display:"flex",gap:20}}>
              {[{label:"Prepared by",name:"Sarah Chen",role:"Senior Accountant",date:"Jan 2, 2025"},{label:"Approved by",name:"James Okafor",role:"Controller",date:"Jan 2, 2025"}].map(sig=>(
                <div key={sig.label} style={{flex:1,padding:"12px 14px",borderRadius:7,border:`1px solid ${T.border}`,background:T.appBg}}>
                  <div style={{...SANS,fontSize:10,fontWeight:700,color:T.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{sig.label}</div>
                  <div style={{...SANS,fontWeight:700,fontSize:13,color:T.textPrimary}}>{sig.name}</div>
                  <div style={{...SANS,fontSize:11,color:T.textMuted,marginTop:2}}>{sig.role} · {sig.date}</div>
                </div>
              ))}
            </div>
          </Section>
        </div>
      </div>
    </div>
  );
}

