import type { ValidationRule } from "../types/filing";

export const FORM_PF_RULES: ValidationRule[] = [
  {
    id: "PF-001",
    form_type: "FORM_PF",
    scope: "filing",
    stage: "pre_submission",
    severity: "error",
    condition: "adviser_profile.eligibility_status !== 'eligible'",
    message: "Adviser is not eligible to file Form PF. Eligibility status must be 'eligible' before submission.",
    remediation: "Verify that the adviser meets the regulatory AUM threshold and eligibility criteria under Rule 204(b)-1. Update eligibility_status to 'eligible' after confirmation.",
    source_reference: "Form PF General Instructions, Rule 204(b)-1(b)",
  },
  {
    id: "PF-002",
    form_type: "FORM_PF",
    scope: "filing",
    stage: "pre_submission",
    severity: "error",
    condition: "adviser_profile.private_fund_assets_aum < 150000000",
    message: "Private fund AUM is below the $150 million filing threshold. Form PF is not required for advisers below this threshold.",
    remediation: "Confirm whether the adviser is required to file Form PF. If private fund AUM is genuinely below $150 million, this filing should be withdrawn.",
    source_reference: "Form PF General Instructions, Rule 204(b)-1(a)(1)",
  },
  {
    id: "PF-003",
    form_type: "FORM_PF",
    scope: "section",
    stage: "pre_submission",
    severity: "warning",
    condition: "section.applicable_to does not include filer_category AND section.items.length > 0",
    message: "A form section contains data entries but is not applicable to this filer's category. Inapplicable sections should remain empty.",
    remediation: "Review the filer_category assignment and remove any data entered in sections not applicable to that category, or correct the filer_category if it is misclassified.",
    source_reference: "Form PF General Instructions — Section Applicability Table",
  },
  {
    id: "PF-004",
    form_type: "FORM_PF",
    scope: "cross_field",
    stage: "pre_submission",
    severity: "error",
    condition: "SUM(fund.net_asset_value) delta vs derived_metrics aggregate > 0.01%",
    message: "Aggregate net asset value reported in derived metrics does not reconcile to the sum of per-fund NAV values. Discrepancy exceeds 0.01% tolerance.",
    remediation: "Reconcile each fund's net_asset_value to the derived_metrics aggregates. Identify the fund(s) with mismatched values and correct the source data.",
    source_reference: "Form PF Instructions, Section 1b — Aggregate Reporting",
  },
  {
    id: "PF-005",
    form_type: "FORM_PF",
    scope: "filing",
    stage: "pre_submission",
    severity: "error",
    condition: "counterparties.length === 0 AND filer_category === 'large_hedge_fund_adviser'",
    message: "No counterparty records found. Large hedge fund advisers must report counterparty exposure data.",
    remediation: "Add counterparty exposure records for all qualifying counterparties. Obtain data from prime brokerage, ISDA, and repo agreements.",
    source_reference: "Form PF Instructions, Section 2a — Counterparty Exposure",
  },
  {
    id: "PF-006",
    form_type: "FORM_PF",
    scope: "submission",
    stage: "pre_submission",
    severity: "error",
    condition: "reporting_period.due_date < today AND submission_status !== 'submitted' AND submission_status !== 'accepted'",
    message: "The filing due date has passed and this filing has not been submitted. The filing is overdue.",
    remediation: "Submit the filing immediately. If an extension was requested, verify the extension was granted and update the due date accordingly.",
    source_reference: "Form PF General Instructions — Filing Deadlines",
  },
  {
    id: "PF-007",
    form_type: "FORM_PF",
    scope: "filing",
    stage: "pre_submission",
    severity: "warning",
    condition: "amendment_indicator === true AND prior_filing_reference is absent in envelope",
    message: "This filing is marked as an amendment but no prior filing reference is provided in the envelope. Amendment filings must reference the original filing.",
    remediation: "Populate the prior filing reference field in the filing envelope with the filing_id or accession number of the original filing being amended.",
    source_reference: "Form PF General Instructions — Amendment Filings",
  },
  {
    id: "PF-008",
    form_type: "FORM_PF",
    scope: "field",
    stage: "pre_submission",
    severity: "error",
    condition: "FieldValue.data_type === 'percentage' AND (value < 0 OR value > 100)",
    message: "A percentage field contains a value outside the valid range of 0 to 100.",
    remediation: "Correct the percentage value to fall within 0–100. If the value represents leverage or a ratio that can exceed 100%, verify the correct data_type is assigned.",
    source_reference: "Form PF General Instructions — Data Type Validation",
  },
  {
    id: "PF-009",
    form_type: "FORM_PF",
    scope: "field",
    stage: "pre_submission",
    severity: "error",
    condition: "FieldValue.data_type === 'date' AND value fails ISO 8601 format check",
    message: "A date field contains a value that is not a valid ISO 8601 date (YYYY-MM-DD).",
    remediation: "Correct the date value to conform to ISO 8601 format (YYYY-MM-DD). Check the source system's date formatting for this field.",
    source_reference: "Form PF General Instructions — Data Type Validation",
  },
  {
    id: "PF-010",
    form_type: "FORM_PF",
    scope: "submission",
    stage: "pre_submission",
    severity: "error",
    condition: "attestations.signed_off !== true",
    message: "The filing attestation has not been completed. All Form PF filings require a signed attestation prior to submission.",
    remediation: "Have the authorized signatory review and complete the attestation. Ensure the approved_by field is populated and signed_off is set to true.",
    source_reference: "Form PF General Instructions — Attestation Requirements",
  },
];

export const FORM_N_PORT_RULES: ValidationRule[] = [
  {
    id: "NP-001",
    form_type: "FORM_N_PORT",
    scope: "submission",
    stage: "pre_submission",
    severity: "error",
    condition: "submission_metadata.package_format !== 'xml'",
    message: "The submission package format is not XML. Form N-PORT filings must be submitted in EDGAR-compliant XML format.",
    remediation: "Re-export the filing package in EDGAR XML format. Verify the submission channel and format configuration in the filing system.",
    source_reference: "Form N-PORT EDGAR Filing Requirements, Rule 30b1-9",
  },
  {
    id: "NP-002",
    form_type: "FORM_N_PORT",
    scope: "filing",
    stage: "pre_submission",
    severity: "error",
    condition: "registrant.reporting_period_end is not the last calendar day of a month",
    message: "The reporting period end date is not the last day of a calendar month. Form N-PORT must report as of the last business/calendar day of a month.",
    remediation: "Correct the reporting_period_end to reflect the last day of the applicable month. Verify the fund's fiscal month-end date.",
    source_reference: "Form N-PORT Instructions, Part A — Reporting Period",
  },
  {
    id: "NP-003",
    form_type: "FORM_N_PORT",
    scope: "field",
    stage: "pre_submission",
    severity: "error",
    condition: "holding.identifier.cusip is null AND holding.identifier.isin is null AND holding.identifier.ticker is null",
    message: "A holding record has no security identifier. At least one of CUSIP, ISIN, or ticker must be provided for each holding.",
    remediation: "Add at least one valid security identifier (CUSIP, ISIN, or ticker) to the holding. Cross-reference with the fund's security master or custodian records.",
    source_reference: "Form N-PORT Instructions, Part C — Investment Information",
  },
  {
    id: "NP-004",
    form_type: "FORM_N_PORT",
    scope: "cross_field",
    stage: "pre_submission",
    severity: "error",
    condition: "SUM(holding.value) by series_id delta vs series.net_assets > 0.1%",
    message: "The sum of holding values for a series does not reconcile to the series net assets. Discrepancy exceeds 0.1% tolerance.",
    remediation: "Reconcile the holding values for each series to the reported net assets. Check for missing holdings, incorrect valuations, or stale prices.",
    source_reference: "Form N-PORT Instructions, Part B — Net Asset Value",
  },
  {
    id: "NP-005",
    form_type: "FORM_N_PORT",
    scope: "field",
    stage: "pre_submission",
    severity: "error",
    condition: "holding.pct_net_assets < 0 OR holding.pct_net_assets > 100",
    message: "A holding's percentage of net assets is outside the valid range of 0 to 100.",
    remediation: "Recalculate pct_net_assets as (holding.value / series.net_assets) * 100. Verify the holding value and net assets figures used in the calculation.",
    source_reference: "Form N-PORT Instructions, Part C — Percentage of Net Assets",
  },
  {
    id: "NP-006",
    form_type: "FORM_N_PORT",
    scope: "cross_field",
    stage: "pre_submission",
    severity: "error",
    condition: "duplicate holding_id values detected across holdings array",
    message: "Duplicate holding_id values were detected. Each holding must have a unique identifier.",
    remediation: "Assign unique holding_id values to all holdings. Review the data pipeline or ETL process that generates holding IDs for the source of duplication.",
    source_reference: "Form N-PORT Instructions, Part C — Record Identification",
  },
  {
    id: "NP-007",
    form_type: "FORM_N_PORT",
    scope: "filing",
    stage: "pre_submission",
    severity: "warning",
    condition: "amendment_indicator === true AND effective_date logic check fails",
    message: "This filing is marked as an amendment but the effective date does not align with the expected amendment filing timeline.",
    remediation: "Verify the amendment_indicator setting and the effective_date. Ensure the amendment references the correct original filing period and that the effective_date is within the permissible amendment window.",
    source_reference: "Form N-PORT Instructions — Amendment Filing Requirements",
  },
  {
    id: "NP-008",
    form_type: "FORM_N_PORT",
    scope: "cross_field",
    stage: "pre_submission",
    severity: "error",
    condition: "SUM(liquidity buckets) delta vs total portfolio value > 0.1%",
    message: "The sum of liquidity bucket values does not reconcile to the total portfolio value. Discrepancy exceeds 0.1% tolerance.",
    remediation: "Ensure every holding is assigned a liquidity classification (1–4) and that the sum of values across all buckets equals the total portfolio value within the 0.1% tolerance.",
    source_reference: "Form N-PORT Instructions, Part D — Liquidity Risk Management",
  },
  {
    id: "NP-009",
    form_type: "FORM_N_PORT",
    scope: "field",
    stage: "pre_submission",
    severity: "error",
    condition: "holding.value is null or undefined",
    message: "A holding record has a null or undefined value. All holdings must have a reported fair market value.",
    remediation: "Populate the value field for all holdings using the fund's pricing source. Investigate any holdings that could not be priced and apply appropriate fair value procedures.",
    source_reference: "Form N-PORT Instructions, Part C — Fair Value",
  },
  {
    id: "NP-010",
    form_type: "FORM_N_PORT",
    scope: "submission",
    stage: "pre_submission",
    severity: "error",
    condition: "submission_status !== 'ready_to_file' AND submission_status !== 'submitted'",
    message: "The filing submission status is not in a valid state for transmission. Filing must be in 'ready_to_file' or 'submitted' status.",
    remediation: "Complete all required review and approval steps to advance the filing to 'ready_to_file' status before attempting submission.",
    source_reference: "Form N-PORT EDGAR Filing Requirements — Submission Workflow",
  },
];
